services:
  metanoia-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
        - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    container_name: metanoia_app
    restart: always
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
    networks:
      - metanoia_network

networks:
  metanoia_network:
    driver: bridge
